const test=require('node:test'),assert=require('node:assert/strict');
const d=require('../.test-build/src/lib/domain.js');
const p={id:'00000000-0000-4000-8000-000000000001',title:'Tas',price:100000,image_url:'https://example.com/a.jpg',images:[],variants:[{name:'Hitam',image:''}],stock:8,is_active:true};
test('same product and variant merge quantities',()=>{const a=d.addCartLine([],p,'Hitam');assert.equal(d.addCartLine(a,p,'Hitam')[0].quantity,2)});
test('different variants remain distinct',()=>{const b={...p,variants:[...p.variants,{name:'Putih',image:''}]};assert.equal(d.addCartLine(d.addCartLine([],b,'Hitam'),b,'Putih').length,2)});
test('variant is mandatory when product has variants',()=>assert.throws(()=>d.addCartLine([],p,'')));
test('unknown variant cannot enter cart',()=>assert.throws(()=>d.addCartLine([],p,'fake')));
test('out of stock is rejected',()=>assert.throws(()=>d.addCartLine([],{...p,stock:0},'Hitam')));
test('inactive product is rejected',()=>assert.throws(()=>d.addCartLine([],{...p,is_active:false},'Hitam')));
test('quantities are integers only',()=>assert.throws(()=>d.setCartQuantity(d.addCartLine([],p,'Hitam'),p.id,'Hitam',1.5)));
test('empty cart is rejected',()=>assert.throws(()=>d.checkoutItems([])));
test('checkout serializes no price or customer-controlled totals',()=>{const v=d.checkoutItems(d.addCartLine([],p,'Hitam'));assert.deepEqual(Object.keys(v[0]).sort(),['product_id','quantity','variant']);});
test('display shipping threshold',()=>{assert.deepEqual(d.cartTotals(d.addCartLine([],p,'Hitam'),10000,100000),{subtotal:100000,shipping:0,total:100000});});
test('Indonesian phone normalization',()=>assert.equal(d.normalizePhone('0812-3456-7890'),'6281234567890'));
test('phone invalid input rejected',()=>assert.throws(()=>d.normalizePhone('abc')));
test('URL javascript not accepted',()=>assert.equal(d.safeImageUrl('javascript:alert(1)'),''));
test('data URLs not accepted',()=>assert.equal(d.safeImageUrl('data:image/svg+xml,anything'),''));
test('secure image URL preserved',()=>assert.equal(d.safeImageUrl('https://example.com/a.png'),'https://example.com/a.png'));
test('WA message encoded as a whole, including & and new lines',()=>{const url=d.whatsappUrl('6281234567890','A&B\n#order');assert.equal(new URL(url).searchParams.get('text'),'A&B\n#order')});
test('CSV formula injection is neutralized',()=>assert.equal(d.csvCell('=1+1'),'"\'=1+1"'));
test('corrupt stored cart is discarded',()=>assert.deepEqual(d.parseCart('bad'),[]));
test('stored cart survives roundtrip',()=>{const cart=d.addCartLine([],p,'Hitam');assert.deepEqual(d.parseCart(JSON.stringify(cart)),cart)});
test('hostile stored qty is discarded',()=>assert.deepEqual(d.parseCart(JSON.stringify([{...d.addCartLine([],p,'Hitam')[0],quantity:1e9}])),[]));
test('customer fields validated',()=>assert.throws(()=>d.validateCustomer({name:'',phone:'081234567890',address:'Jalan',note:''})));
