const test=require('node:test'),assert=require('node:assert/strict');
const v=require('../.test-build/supabase/functions/_shared/validation.js');
const ID='00000000-0000-4000-8000-000000000001';
const input=()=>({customer:{name:'Uji',address:'Alamat lengkap pengujian',phone:'6281234567890',note:''},methodId:ID,items:[{product_id:ID,quantity:1,variant:''}]});
test('checkout ignores tampered client price',()=>{const b=input();b.items[0].price=1;b.total=1;assert.equal('price' in v.checkoutInput(b).items[0],false)});
for(const q of [0,-1,1.1,100,'2',null])test(`reject invalid quantity ${q}`,()=>{const b=input();b.items[0].quantity=q;assert.throws(()=>v.checkoutInput(b));});
test('duplicate cart line rejected server side',()=>{const b=input();b.items.push({...b.items[0]});assert.throws(()=>v.checkoutInput(b));});
test('malformed UUID rejected',()=>assert.throws(()=>v.uuid('../admin')));
test('receipt proof requires 256 bit hex value',()=>assert.throws(()=>v.proof('short')));
test('settlement and code 200 is paid',()=>assert.equal(v.gatewayStatus({transaction_status:'settlement',status_code:'200'}),'paid'));
test('capture challenge must not become paid',()=>assert.equal(v.gatewayStatus({transaction_status:'capture',status_code:'200',fraud_status:'challenge'}),'pending'));
test('capture accept can become paid',()=>assert.equal(v.gatewayStatus({transaction_status:'capture',status_code:'200',fraud_status:'accept'}),'paid'));
test('settlement denied does not become paid',()=>assert.equal(v.gatewayStatus({transaction_status:'settlement',status_code:'200',fraud_status:'deny'}),'pending'));
test('non-success code does not become paid',()=>assert.equal(v.gatewayStatus({transaction_status:'settlement',status_code:'201'}),'pending'));
test('fractional money rejected',()=>assert.throws(()=>v.integerMoney('100.55')));
test('decimal provider representation accepted',()=>assert.equal(v.integerMoney('100.00'),100));
test('non-finite and exponent money rejected',()=>assert.throws(()=>v.integerMoney('1e20')));
test('signature comparison rejects unequal length',()=>assert.equal(v.equalHex('abcd','abc'),false));
test('GET status with no currency remains valid IDR response',()=>assert.doesNotThrow(()=>v.verifyGatewayData({order_id:'ZYHA-'+ID,transaction_id:ID,gross_amount:'100.00'},'ZYHA-'+ID,100)));
test('GET status explicitly wrong currency is rejected',()=>assert.throws(()=>v.verifyGatewayData({order_id:'ZYHA-'+ID,transaction_id:ID,gross_amount:'100.00',currency:'USD'},'ZYHA-'+ID,100)));
test('GET status amount must match server order',()=>assert.throws(()=>v.verifyGatewayData({order_id:'ZYHA-'+ID,transaction_id:ID,gross_amount:'1.00'},'ZYHA-'+ID,100)));
test('GET status other order cannot update current order',()=>assert.throws(()=>v.verifyGatewayData({order_id:'other',transaction_id:ID,gross_amount:'100.00'},'ZYHA-'+ID,100)));
const snapOrder=()=>({id:ID,gateway_order_id:'ZYHA-'+ID,total_price:210000,shipping_fee:10000,customer_name:'Pembeli',customer_phone:'6281234567890',customer_address:'Alamat '.repeat(100),items:[{product_id:ID,title:'Tas KHAKI',unit_price:100000,quantity:1},{product_id:ID,title:'Tas BLACK',unit_price:100000,quantity:1}]});
test('Snap item IDs remain unique for two variants of same product',()=>{const x=v.buildSnapPayload(snapOrder());assert.equal(new Set(x.item_details.map(i=>i.id)).size,3)});
test('Snap address is limited while full shipping address remains in order',()=>{const o=snapOrder();const x=v.buildSnapPayload(o);assert.ok(x.customer_details.shipping_address.address.length<=255);assert.ok(o.customer_address.length>255)});
test('Snap totals equal stored order and request 3DS',()=>{const x=v.buildSnapPayload(snapOrder());assert.equal(x.item_details.reduce((s,i)=>s+i.price*i.quantity,0),x.transaction_details.gross_amount);assert.equal(x.credit_card.secure,true)});
test('Snap rejects an inconsistent stored total',()=>assert.throws(()=>v.buildSnapPayload({...snapOrder(),total_price:1}),/nominal/i));
test('Large Snap payload is collapsed without altering amount or stored items',()=>{const o=snapOrder();o.items=Array.from({length:50},(_,i)=>({product_id:ID,title:'Tas '+ '界'.repeat(100),unit_price:100000,quantity:1}));o.total_price=5010000;const x=v.buildSnapPayload(o);assert.ok(new TextEncoder().encode(JSON.stringify(x)).length<=15000);assert.equal(x.item_details.reduce((s,i)=>s+i.price*i.quantity,0),5010000);assert.equal(o.items.length,50)});
