const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const read = p => fs.existsSync(p) ? fs.readFileSync(p,'utf8') : '';
test('admin route uses a real Auth gate',()=>assert.match(read('Admin.tsx'),/AdminGate/));
test('browser never writes paid directly',()=>assert.doesNotMatch(read('App.tsx'),/\.update\(\{\s*status:\s*['"]paid/));
test('old public settings server-key field is absent',()=>assert.doesNotMatch(read('Admin.tsx'),/midtrans_server_key/));
test('no decorative icon dependency in UI',()=>assert.doesNotMatch(read('App.tsx')+read('Admin.tsx'),/lucide-react|icon="✨"/));
test('one shot SQL exists and uses authoritative pricing',()=>assert.match(read('supabase-setup.sql'),/zyha_place_order/));
test('setup does not seed fake products or orders',()=>assert.doesNotMatch(read('supabase-setup.sql'),/insert into public\.(products|orders)\s*\([^;]*?values\s*\(['"]/i));
test('normal build requires typecheck',()=>assert.match(JSON.parse(read('package.json')).scripts.build,/typecheck/));
test('all relative modules are packaged',()=>require('node:child_process').execFileSync(process.execPath,['scripts/check-files.cjs'],{stdio:'pipe'}));
test('orders have no browser INSERT/UPDATE grants',()=>assert.doesNotMatch(read('supabase-setup.sql'),/grant\s+(?:all|insert|update)[^;]*on public\.orders[^;]*to (?:anon|authenticated)/i));
test('guest SQL RPCs are revoked from browser roles',()=>assert.match(read('supabase-setup.sql'),/revoke all on function public\.zyha_rate_limit[^;]+from public,anon,authenticated/s));
test('admin authorization never reads editable metadata',()=>assert.doesNotMatch(read('supabase-setup.sql').replace(/--[^\n]*/g,''),/user_metadata/));
test('setup stops on unrelated existing schema',()=>assert.match(read('supabase-setup.sql'),/ZYHA_SETUP_REQUIRES_EMPTY_PROJECT/));
test('idempotent checkout is serialized before insert',()=>assert.match(read('supabase-setup.sql'),/pg_advisory_xact_lock\(hashtextextended\(p_request_id/));
test('stock locks follow deterministic ordering',()=>assert.match(read('supabase-setup.sql'),/order by id for update/));
test('receipt proof is hashed and not public table access',()=>assert.match(read('supabase-setup.sql'),/receipt_hash=encode\(extensions\.digest\(p_receipt_token,'sha256'\)/));
test('payment mode is snapshotted per order',()=>assert.match(read('supabase-setup.sql'),/'gateway_mode',s.midtrans_mode/));
test('webhook verifies status server to server',()=>{const s=read('supabase/functions/midtrans-webhook/index.ts');assert.match(s,/equalHex\(signature,\s*expected\)/);assert.match(s,/await syncPayment\(db,\s*order[,)]/);});
test('browser callback never asserts payment success',()=>assert.doesNotMatch(read('src/shop/payment.ts'),/status:\s*['"]paid|Pembayaran Berhasil/));
test('gallery file uploads validate byte signatures',()=>{const s=read('src/lib/api.ts');assert.match(s,/137,80,78,71,13,10,26,10/);assert.match(s,/file.size\s*>\s*5\s*\*\s*1024\s*\*\s*1024/);});
test('application does not use former Supabase endpoint',()=>assert.doesNotMatch(read('supabaseClient.ts'),/hkhajycblrfslxnapogx/));
test('tailwind is built locally, not CDN script',()=>assert.doesNotMatch(read('index.html'),/cdn.tailwindcss.com/));
test('order inputs on frontend never set payment status',()=>assert.doesNotMatch(read('src/lib/api.ts'),/\.from\(['"]orders['"]\)\.update/));
test('unstarted gateway cancellation rejects every recorded payment attempt even after its lease expires',()=>{const s=read('supabase-setup.sql');const fn=s.match(/create or replace function public\.zyha_cancel_unstarted\([\s\S]*?end \$\$;/)[0];assert.match(fn,/for update/);assert.match(fn,/p_version is null or r.version<>p_version/);assert.match(fn,/r.snap_token is not null or r.gateway_transaction_id is not null or r.payment_lock_id is not null or r.payment_lock_until>now\(\)/);assert.match(fn,/r.created_at>now\(\)-interval '5 minutes'/);assert.match(s,/revoke all on function public\.zyha_cancel_unstarted[^;]+from public,anon,authenticated/);});
test('duplicate auth sign-in does not unmount an existing admin workspace',()=>assert.match(read('src/components/AdminGate.tsx'),/event\s*===\s*'SIGNED_IN'\s*&&\s*authUser.current\s*!==\s*nextSession\?\.user.id/));
test('server normalizes variant names without changing customer data',()=>assert.match(read('supabase-setup.sql'),/new.variants=coalesce\(\(select jsonb_agg\(jsonb_build_object\('name',btrim/));
test('bootstrap email does not collide with auth.users.email column',()=>{const s=read('supabase-setup.sql');assert.match(s,/lower\(auth\.users\.email\)=lower\(v_admin_email\)/);assert.doesNotMatch(s,/declare email text=/);});
test('catalog URL pagination is a nonnegative integer',()=>assert.match(read('App.tsx'),/Math\.floor\(Number\(params\.get\('page'\)\)/));
